use_frameworks!

platform :ios, '9.0'

target 'FrameWorkIphoneos_Example' do
  pod 'FrameWorkIphoneos', :path => '../'

  target 'FrameWorkIphoneos_Tests' do
    inherit! :search_paths

    
  end
end
